### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by erlandsona** [kasselTrankos/copyfilemon-brunch#1]
node --version -> 4.2.2
brunch -V -> 1.8.5 & 2.0.4

config.coffee

```
exports.config =
  # See http://brunch.io/#documentation for docs.
  server:
    port: 8100

  modules:
    definition: false
    wrapper: false

  paths:
    public: 'www'

  conventions:
    ignored: [
      /app\/styles[\\/]_/
      /test/
    ]

  files:
    javascripts:
      defaultExtension: 'coffee'
      joinTo:
        'js/app.js': /^app/
        'js/vendor.js': /^(bower_components|vendor)/

    stylesheets:
      defaultExtension: 'scss'
      joinTo:
        'css/app.css': /^app/

    templates:
      defaultExtension: 'html'
      joinTo:
        'js/app.js': /^app/

  plugins:
    copyfilemon:
      'www/fonts': 'bower_components/ionic/fonts'
    html2js:
      options:
        base: 'app/features'
```
